docs/Quickstart Guide/(3) Stroop Block.ipynb
docs/Quickstart Guide/(4) Responses and Feedback.ipynb
docs/Quickstart Guide/Mastery.ipynb
docs/Quickstart Guide/index.md
docs/User Guide/data_variables.md
docs/User Guide/llm_synthetic_participant.md
docs/index.md

The PR includes some doc fixes, such as
- fixing typos and grammar
- adding some context on parts that seemed under-explained

doc: general documentation fixes and amendments

---

docs/Basic Tutorials/(1) First Experiment.ipynb
docs/Basic Tutorials/(2) Instruction Block.ipynb
docs/Basic Tutorials/(3) Stroop Block.ipynb
docs/Use Case Tutorials/AI Alignment/Trolley Problem.ipynb
docs/Use Case Tutorials/Psychophysics/sweetpea.ipynb

docs: clear output of notebooks

---

docs/Use Case Tutorials/AI Alignment/Reinforcement Learning with Certainty.ipynb
docs/Use Case Tutorials/AI Alignment/Reinforcement Learning.ipynb
docs/User Guide/llm_synthetic_participant.md
src/sweetbean/experiment.py
src/sweetbean/stimulus/Choice.py
src/sweetbean/stimulus/Stimulus.py

feat: add certainty for llm

---

docs/User Guide/overview.md

fixed issue #63 
- **fix**: A typo in user guild/overview
If this is a breaking change (which might apply to any of the other kinds of change), note that below, otherwise delete 
this section:
- **BREAKING_CHANGE**: {description}
> Update the title of the PR to follow the convention:
> `{type}{! if BREAKING_CHANGE}: {short description}`, e.g. 
> - "fix: add missing foo in module bar" 
> - "feat: new theorist abc",
> - "feat!: replace module x with module y"
> - "docs: add notebooks on theorist z" 
> 
> ... then delete this block.
- bulleted list of features, …

fix typo in file referencing in user guild/overview

---

docs/Use Case Tutorials/AI Piloting/Bandit Task with Target Value.ipynb
docs/Use Case Tutorials/AI Piloting/index.md
src/sweetbean/experiment.py
src/sweetbean/stimulus/Stimulus.py
src/sweetbean/util/parse.py
src/sweetbean/variable/__init__.py

Various fixes

---

docs/Use Case Tutorials/AI Piloting/Bandit Task with Target Value.ipynb

docs: fix pip install in notebook

---

docs/Stimuli/image/image_language.py
src/sweetbean/stimulus/Image.py

docs: add language support for images

---

docs/index.md

doc: add debugging tip

---

docs/User Guide/index.md

doc: add installation guide

---

paper/paper.bib

doc: fix bib file

---

src/sweetbean/experiment.py

feat: add support for download data as csv files

---

docs/User Guide/overview.md

docs: add documentation for local data storage

---

src/sweetbean/util/parse.py

bug: remove replace format (only complicates things)

---

docs/Notebooks/tst.py
src/sweetbean/experiment.py
src/sweetbean/util/prompts.py

feat: add preamble and demographic util

---

src/sweetbean/stimulus/Stimulus.py

fix get data variable to recursiely get boolean side effect true or not
- resolves #117

feat: fix recursive get data variable

---

docs/Stimuli/generic/generic.py
docs/Stimuli/index.md
src/sweetbean/stimulus/Generic.py
src/sweetbean/stimulus/__init__.py

119 create generic js stimulus

---

tests/test_stimuli.py

feat: make warning better

---

docs/Stimuli/generic/generic.py

doc: remove duplicate

---

docs/Stimuli/generic/generic.py
docs/Stimuli/index.md

docs: add hint to pre-release

---

README.md
docs/installation.md
mkdocs.yml

Add compatibility documentation

doc: add installation/compatibility to documentation

---

.github/workflows/test-pytest.yml
README.md
docs/installation.md
paper/paper.md
pyproject.toml
tests/test_stimuli.py

131 update paper

---

src/sweetbean/util/parse.py

add error checking

---

README.md
docs/installation.md
src/sweetbean/__init__.py

add java dependency

---

CITATION.cff
README.md
docs/index.md

add citation

---

docs/Extensions/Touchscreen/index.md
docs/Extensions/Touchscreen/touchbutton.py
docs/Extensions/index.md
mkdocs.yml
pyproject.toml
src/sweetbean/block.py
src/sweetbean/experiment.py
src/sweetbean/extension/TouchButton.py
src/sweetbean/extension/__init__.py
src/sweetbean/stimulus/Stimulus.py
src/sweetbean/util/data_process.py
src/sweetbean/util/parse.py

add touchscreen extension and data processing

add touch extension and data processing

---

src/sweetbean/extension/TouchButton.py
src/sweetbean/util/data_process.py

Add documentation

---

src/sweetbean/experiment.py

fix to-js-string

---

src/sweetbean/util/data_process.py

> 
> ... then delete this block.
- bulleted list of features, describing the code contributions in this pull request
- potential questions for the code reviewer (e.g., if you want feedback on a certain method or class; any feedback required from other code contributors with their mentioning)
- any additional remarks for the code reviewer
- if your remarks or questions pertain to individual lines in the code, you may also include them as comments in the code review window
If your PR is related to UI change or anything visual, feel free to include screenshots to give the reviewer straightforward understandings on your changes.

fix data process
